### ISSUE TITLE
Add Houston

### ISSUE THREAD

**Issue by SteveChenDC** [CodeandCoffeeCommunity/Barista-bot#40]
# New Chapter Bot Setup

#### City Name

Name: Houston

#### City Emoji

Emoji: @abe-101 should we remove this section? I don't think this is useful in the current button direction we're going in and folks do not feel too attached to these emojis.

#### Role Number

Number: 1074894021790543902

## Checklist For Setting Up New Chapters

Set up in Discord:
 - [x] Chapter role
 - [ ] Chapter category 
 - [ ] General chapter channel accessible by the `@chapter` role
 - [ ] Private chapter channel accessible by the roles `@Core` and `@Organizer`
 - [ ] Add new chapter to to Welcome message

Bot configuration:
 - [ ] Add chapter role and emoji to the bot source code

**Comment by abe-101** [comment]
@SteveChenDC can you update the role # for Houston
`1074898462547648623`
