### ISSUE TITLE
New Chapter: Frederick (MD)

### ISSUE THREAD

**Issue by SteveChenDC** [CodeandCoffeeCommunity/Barista-bot#45]
# New Chapter Bot Setup

#### City Name

Name: Frederick (MD)

#### Role Number

Number:
1024892173310767186

## Checklist For Setting Up New Chapters

Set up in Discord:
 - [x] Chapter role
 - [x] Chapter category 
 - [] General chapter channel accessible by the `@chapter` role
 - [] Private chapter channel accessible by the roles `@Core` and `@Organizer`
 - [] Add new chapter to to Welcome message

Bot configuration:
 - [ ] Add chapter role and emoji to the bot source code

**Comment by abe-101** [comment]
https://discord.com/channels/894703368411422790/917314653992923146/1076658296137723924

**Comment by SteveChenDC** [comment]
Closing! Manually created channels for Frederick as it's under the DC/MD/VA category
