### ISSUE TITLE
New Chapter: Conneticut

### ISSUE THREAD

**Issue by SteveChenDC** [CodeandCoffeeCommunity/Barista-bot#67]
# New Chapter Bot Setup

#### City Name

Name: Conneticut

#### Role Number

Number: <@&1193739841859485758>

## Checklist For Setting Up New Chapters

Set up in Discord:
 - [x] Chapter role
 - [x] Chapter category 
 - [x] General chapter channel accessible by the `@chapter` role
 - [x] Private chapter channel accessible by the roles `@Core` and `@Organizer`
 - [x] Add new chapter to to Welcome message

Bot configuration:
 - [x] Add chapter role and emoji to the bot source code

**Comment by abe-101** [comment]
Is this complete? can we close it?

**Comment by SteveChenDC** [comment]
@abe-101 yes!
